In [28]:
from sklearn.model_selection import train_test_split
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)


from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.01, max_iter=100000)
lasso_reg.fit(X_train, y_train)
lasso_reg.score(X_train, y_train) # 0.29323768991114596
lasso_reg.score(X_test, y_test) # 0.2093750325527227
np.sum(lasso_reg.coef_ != 0) # Number of features used - 4



33

In [29]:
import numpy as np

In [30]:
lasso_reg.score(X_train, y_train)

0.89650695597512908

In [31]:
lasso_reg.score(X_test, y_test)

0.76564898878435228

In [32]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [33]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [34]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [ ]:
lin_reg.score(X)

In [35]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [36]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [37]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [38]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [39]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [44]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC(C=0.01)
lin_svc.fit(X, y)

LinearSVC(C=0.01, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [45]:
lin_svc.score(X, y)

0.92307692307692313

In [46]:

from sklearn.datasets import make_blobs

X, y = make_blobs(random_state=42)

In [47]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression(C=1)
log_clf.fit(X, y)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [50]:
log_clf.coef_

array([[-0.6048619 ,  0.87084832],
       [ 1.36873029, -0.28733353],
       [-0.72901307, -0.93425973]])

In [52]:
log_clf.predict_proba(X)

array([[  6.28289405e-03,   3.19128811e-04,   9.93397977e-01],
       [  6.15551193e-03,   9.87057624e-01,   6.78686390e-03],
       [  9.97920561e-01,   1.22404122e-03,   8.55397799e-04],
       [  3.73656846e-03,   9.91054109e-01,   5.20932284e-03],
       [  1.80314846e-02,   9.02241917e-04,   9.81066273e-01],
       [  3.10888002e-02,   9.55733793e-01,   1.31774067e-02],
       [  9.96458875e-01,   3.22300695e-03,   3.18117560e-04],
       [  4.27443120e-02,   9.54073272e-01,   3.18241587e-03],
       [  5.81440341e-02,   9.40448316e-01,   1.40765031e-03],
       [  9.97853032e-01,   5.05520827e-04,   1.64144735e-03],
       [  9.97398840e-01,   1.25016979e-03,   1.35099063e-03],
       [  3.59906648e-02,   5.98371037e-04,   9.63410964e-01],
       [  1.31043600e-02,   1.22380660e-03,   9.85671833e-01],
       [  9.92326452e-01,   8.40108062e-04,   6.83344002e-03],
       [  9.92460411e-01,   7.04016246e-03,   4.99426738e-04],
       [  3.83155010e-02,   1.28071109e-04,   9.6155642

In [53]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [54]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [55]:
knn_clf.score(X_train, y_train)

0.94736842105263153

In [56]:
knn_clf.score(X_test, y_test)

0.8571428571428571

In [57]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [58]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [59]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [60]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [72]:

from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

log_reg = LogisticRegression(C=0.01)
log_reg.fit(X_train, y_train)
log_reg.score(X_train, y_train) # .95


0.93427230046948362

In [73]:
log_reg.score(X_test, y_test) # .95

0.93006993006993011

In [74]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [ ]:
from sklearn.linear_model import Lasso

In [88]:
lasso_reg = Lasso(alpha=0.01, max_iter=1000000)
lasso_reg.fit(X_train, y_train)


Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [89]:
lasso_reg.score(X_train, y_train)

0.89650695597512908

In [90]:
lasso_reg.score(X_test, y_test)

0.76564898878435228

In [91]:
(lasso_reg.coef_ != 0).sum()

33

In [92]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [96]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC(C=100)
lin_svc.fit(X, y)

LinearSVC(C=100, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [94]:
lin_svc.score(X, y)

0.92307692307692313

In [97]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [98]:
from sklearn.model_selection import train_test_split

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [100]:
from sklearn.linear_model import LogisticRegression

In [103]:
log_clf = LogisticRegression(C=1)
log_clf.fit(X_train, y_train)

LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [104]:
log_clf.score(X_train, y_train)

0.89473684210526316

In [105]:
log_clf.score(X_test, y_test)

1.0

In [108]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [110]:
lin_reg.intercept_

-0.031804343026759746

In [111]:
lin_reg.coef_

array([ 0.39390555])

In [112]:
from sklearn.datasets import make_blobs

X, y = make_blobs(random_state=42)

In [113]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC(C=1)
lin_svc.fit(X, y)

LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [115]:
lin_svc.score(X, y)

1.0

In [117]:
(lasso_reg.coef_ != 0).sum()

33

In [118]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [140]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.1)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [141]:
ridge_reg.score(X_train, y_train)

0.92857820820107329

In [142]:
ridge_reg.score(X_test, y_test)

0.77179336888449701

In [143]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [144]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [153]:
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_wave(n_samples=40)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=66)


In [157]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=2)
knn_reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=2, p=2,
          weights='uniform')

In [158]:
knn_reg.score(X_train, y_train)

0.88331002669268144

In [159]:
knn_reg.score(X_test, y_test)

0.64781351273112731

In [160]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1)
ridge_reg.fit(X, y)

Ridge(alpha=1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [161]:
ridge_reg.score(X_train, y_test)

0.68555350889171973

In [162]:
ridge_reg.score(X_test, y_test)

0.63224959691493976

In [164]:
from sklearn.tree import DecisionTreeClassifier

In [165]:
from sklearn.tree import DecisionTreeClassifier

In [167]:
from sklearn.tree import DecisionTreeRegressor

In [168]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [191]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=5)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [192]:
tree_clf.score(X_train, y_train)

0.99530516431924887

In [193]:
tree_clf.score(X_test, y_test)

0.93006993006993011

In [175]:

import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [194]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [195]:
from sklearn.tree import export_graphviz

In [196]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [197]:
tree.feature_importances_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.01019737,  0.04839825,  0.        ,  0.        ,  0.0024156 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.72682851,  0.0458159 ,  0.        ,  0.        ,  0.0141577 ,
        0.        ,  0.018188  ,  0.1221132 ,  0.01188548,  0.        ])

In [201]:
list(zip(cancer["feature_names"], tree.feature_importances_))

[('mean radius', 0.0),
 ('mean texture', 0.0),
 ('mean perimeter', 0.0),
 ('mean area', 0.0),
 ('mean smoothness', 0.0),
 ('mean compactness', 0.0),
 ('mean concavity', 0.0),
 ('mean concave points', 0.0),
 ('mean symmetry', 0.0),
 ('mean fractal dimension', 0.0),
 ('radius error', 0.010197368202069328),
 ('texture error', 0.048398253618649398),
 ('perimeter error', 0.0),
 ('area error', 0.0),
 ('smoothness error', 0.002415595085315826),
 ('compactness error', 0.0),
 ('concavity error', 0.0),
 ('concave points error', 0.0),
 ('symmetry error', 0.0),
 ('fractal dimension error', 0.0),
 ('worst radius', 0.72682850946032007),
 ('worst texture', 0.045815897088866304),
 ('worst perimeter', 0.0),
 ('worst area', 0.0),
 ('worst smoothness', 0.014157702104714051),
 ('worst compactness', 0.0),
 ('worst concavity', 0.0181879968644502),
 ('worst concave points', 0.12211319926548449),
 ('worst symmetry', 0.01188547831013032),
 ('worst fractal dimension', 0.0)]

In [198]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [202]:
import pandas as pd
ram_prices = pd.read_csv("datasets/ram_price.csv")
data_train = ram_prices[ram_prices.date < 2000]
data_test = ram_prices[ram_prices.date >= 2000]
# predict prices based on date
X_train = data_train.date[:, np.newaxis]
# we use a log-transform to get a simpler relationship of data ti target
y_train = np.log(data_train.price)
X_all = ram_prices.date[:, np.newaxis]

In [203]:
from sklearn.tree import DecisionTreeRegressor

In [204]:
tree_reg = DecisionTreeRegressor()
tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_split=1e-07,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

In [205]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [211]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(max_depth=4)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [212]:
tree_clf.score(X_train, y_train)

0.98826291079812212

In [213]:
tree_clf.score(X_test, y_test)

0.95104895104895104

In [214]:
tree_clf.feature_importances_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.04839825,  0.        ,  0.0024156 ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.72682851,  0.0458159 ,  0.        ,  0.        ,  0.0141577 ,
        0.        ,  0.018188  ,  0.1221132 ,  0.02208285,  0.        ])

In [215]:
import pandas as pd
ram_prices = pd.read_csv("datasets/ram_price.csv")
data_train = ram_prices[ram_prices.date < 2000]
data_test = ram_prices[ram_prices.date >= 2000]
# predict prices based on date
X_train = data_train.date[:, np.newaxis]
# we use a log-transform to get a simpler relationship of data ti target
y_train = np.log(data_train.price)
X_all = ram_prices.date[:, np.newaxis]

In [216]:
from sklearn.tree import DecisionTreeRegressor

In [217]:
tree_reg = DecisionTreeRegressor()
tree_reg.fit(X,m y)

SyntaxError: invalid syntax (<ipython-input-217-51df2abfeacb>, line 2)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [5]:
from sklearn.datasets import load_breast_cancer

In [9]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [10]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [11]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [12]:
tree_clf.score(X_train, y_train)

1.0

In [13]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [14]:
from sklearn.svm import LinearSVC
svc_clf = LinearSVC()
svc_clf.fit(X, y)


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [15]:
from sklearn.tree import DecisionTreeRegressor

In [16]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [20]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [21]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [22]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [23]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [24]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [25]:
tree.feature_importances_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.01019737,  0.04839825,  0.        ,  0.        ,  0.0024156 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.72682851,  0.0458159 ,  0.        ,  0.        ,  0.0141577 ,
        0.        ,  0.018188  ,  0.1221132 ,  0.01188548,  0.        ])

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn_clf = KNeighborsClassifier()

In [27]:

import mglearn
X, y = mglearn.datasets.make_forge()


In [28]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
ridge_reg = Ridge(alpha=1)
fir

In [33]:
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                   random_state=42)


In [34]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
forest_clf = RandomForestClassifier(n_estimators=10, max_features=100)

In [41]:
forest_clf.estimators_

[]

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
forest_clf = RandomForestClassifier(n_estimators=3, max_depth=4, max_features=2)

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
forest_clf.feature_importances_

NotFittedError: Estimator not fitted, call `fit` before `feature_importances_`.

In [45]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


In [1]:
from sklearn.ensemble import GradientBostingRegressor

ImportError: cannot import name 'GradientBostingRegressor'

In [2]:
from sklearn.ensemble import GradientBoostingClassifier

In [3]:
forest.feature_importance_

NameError: name 'forest' is not defined

In [ ]:
n_estimators

max_depth

max_features



In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
from sklearn.linear_model import Ridge

In [6]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [8]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
cancer.DESCR

'Breast Cancer Wisconsin (Diagnostic) Database\n=============================================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance, field 3 is Mean Rad

In [ ]:
n_estimators

mac_depth

max_featurs

In [9]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [10]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [11]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [12]:
from sklearn.datasets import load_boston

In [14]:
from sklearn.svm import LinearSVC

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
from sklearn.svm import LinearSVC

In [21]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


log_reg = LogisticRegression(C=100)
log_reg.fit(X_train, y_train)
log_reg.score(X_train, y_train) # .95

0.971830985915493

In [22]:
log_reg.score(X_test, y_test) # .95

0.965034965034965

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
np.sum((lasso.coef_ != 0))

NameError: name 'np' is not defined

In [27]:
from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier(n_estimators=100)

In [ ]:
forest.feature_importances_

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
from sklearn.linear_model import Lasso

In [32]:
np.sum(lasso.coef_ != 0)

NameError: name 'np' is not defined

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
from sklearn.ensemble import GradientBoostingClassifier

In [41]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


gbrt = GradientBoostingClassifier(max_depth=1, random_state=0)
gbrt.fit(X_train, y_train)
gbrt.score(X_train, y_train) # 1


0.99061032863849763

In [44]:
gbrt.score(X_test, y_test) # 0.95

0.97202797202797198

In [46]:
gbrt.feature_importances_

array([ 0.  ,  0.05,  0.  ,  0.  ,  0.  ,  0.  ,  0.01,  0.06,  0.01,
        0.  ,  0.  ,  0.01,  0.  ,  0.08,  0.03,  0.  ,  0.06,  0.  ,
        0.02,  0.  ,  0.05,  0.12,  0.07,  0.08,  0.08,  0.  ,  0.05,
        0.09,  0.08,  0.05])

In [ ]:
n_estimators
max_depth
alpha

In [47]:
from sklearn.ensemble import GradientBoostingClassifier

In [49]:
from sklearn.svm import SVC

In [50]:
svc = SVC(kernel="rbf")

In [51]:
from sklearn.svm import SVC

In [53]:
svc_clf = SVC(kernel="rbf", C=1)
svc_clf.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
gr.feature_importande4s_

NameError: name 'gr' is not defined

In [55]:
from sklearn.svm import SVC