In [1]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

In [3]:
cancer.data.shape

(569, 30)

In [6]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [7]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'], 
      dtype='<U23')

In [8]:
from sklearn.datasets import load_boston

In [9]:
boston = load_boston()

In [10]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [14]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], 
      dtype='<U7')

In [15]:
boston.DESCR

"Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n

In [16]:
from sklearn.datasets import load_breast_cancer

In [17]:
cancer = load_breast_cancer()

In [19]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [21]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'], 
      dtype='<U23')

In [23]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0,

In [24]:
from sklearn.datasets import load_boston

In [25]:
boston = load_boston()

In [26]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], 
      dtype='<U7')

In [27]:
boston.data.shape

(506, 13)

In [28]:
boston.DESCR

"Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n

In [29]:
from sklearn.datasets import load_boston

In [30]:
boston = load_boston()

In [37]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [38]:
from sklearn.datasets import load_breast_cancer



In [39]:
cancer = load_breast_cancer()

In [40]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [43]:
cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'], 
      dtype='<U23')

In [44]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [48]:
from sklearn.neighbors import KNeighborsClassifier

In [49]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
knn_clf.predict(X_test)

array([0, 0, 0, 1, 0, 0, 1])

In [50]:
knn_clf.score(X_train, y_train)

0.89473684210526316

In [51]:
knn_clf.score(X_test, y_test)

1.0

In [52]:
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_wave(n_samples=40)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=66)

In [54]:
from sklearn.neighbors import KNeighborsRegressor

In [56]:
knn_reg = KNeighborsRegressor(n_neighbors=4)
knn_reg.fit(X_train, y_train)
knn_reg.predict(X_test)

array([-1.20931128,  0.16239148,  0.23628699, -1.20931128,  1.16978771,
        0.99865866,  0.34718623,  0.34718623, -1.20931128, -0.46949611])

In [57]:
knn_reg.score(X_train, y_train)

0.82921997776107359

In [58]:
knn_reg.score(X_test, y_test)

0.6968950427920706

In [61]:
from sklearn.datasets import load_breast_cancer

In [63]:
cancer = load_breast_cancer()

In [64]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [65]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [66]:
from sklearn.neighbors import KNeighborsClassifier

In [67]:
knn_clf = KNeighborsClassifier(n_neighbors=2)
knn_clf.fit(X_train, y_train)
knn_clf.predict(X_test)

array([0, 0, 0, 0, 0, 1, 0])

In [68]:
knn_clf.score(X_train, y_train)


1.0

In [69]:
knn_clf.score(X_test, y_test)

0.7142857142857143

In [71]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [75]:
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_wave(n_samples=40)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=66)


In [76]:
from sklearn.neighbors import KNeighborsRegressor

In [77]:
knn_reg = KNeighborsRegressor(n_neighbors=3)
knn_reg.fit(X_train, y_train)
knn_reg.predict(X_test)

array([-1.23423166,  0.18400081,  0.49083154, -1.23423166,  1.06165975,
        1.0717713 ,  0.230253  ,  0.230253  , -1.23751806, -0.65851598])

In [79]:
knn_reg.score(X_train, y_train)


0.8366490956884699

In [80]:
knn_reg.score(X_test, y_test)

0.69680253919889323

In [81]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [1]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [5]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)
knn_clf.predict(X_test)

array([1, 0, 1, 0, 1, 0, 1])

In [10]:
knn_clf.score(X_train, y_train)

0.94736842105263153

In [11]:
knn_clf.score(X_test, y_test)

0.8571428571428571

In [12]:
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_wave(n_samples=40)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=66)


In [13]:
from sklearn.neighbors import KNeighborsRegressor

In [14]:
knn_reg = KNeighborsRegressor()
knn_reg.fit(X_train, y_train)


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')

In [15]:
knn_reg.score(X_train, y_train)

0.83908312724093426

In [16]:
knn_reg.score(X_test, y_test)

0.73030519045292408

In [20]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [21]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [23]:
cancer.feature_names


array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'], 
      dtype='<U23')

In [26]:

import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [27]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, y_train, X_test, y_test = train_test_split(X, y)

In [30]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [31]:
cancer.DESCR

'Breast Cancer Wisconsin (Diagnostic) Database\n=============================================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance, field 3 is Mean Rad

In [32]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
knn_clf = KNeighborsClassifier(n_neighbors=3)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [35]:
knn_clf.score(X_train, y_train)

0.94736842105263153

In [36]:
knn_clf.score(X_test, y_test)

0.8571428571428571

In [38]:
from sklearn.neighbors import KNeighborsRegressor

In [39]:
knn_reg = KNeighborsRegressor(n_neighbors=2)
knn_reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=2, p=2,
          weights='uniform')

In [40]:
knn_reg.predict(X_test)

array([ 1.,  1.,  0.,  0.,  0.,  0.,  1.])

In [41]:
knn_reg.score(X_train, y_train)

0.89204545454545459

In [42]:
knn_reg.score(X_test, y_test)

0.29999999999999993

In [43]:
from sklearn.datasets import load_breast_cancer

In [44]:
cancer = load_breast_cancer()

In [45]:
from sklearn.datasets import load_boston
boston = load_boston()

In [46]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [48]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [49]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [50]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [51]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [52]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [53]:
lin_reg.score(X_train, y_train)

0.95235264368642392

In [55]:
lin_reg.score(X_test, y_test)

0.60577548929354275

In [56]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [57]:
lin_reg.intercept_

-0.031804343026759746

In [58]:
lin_reg.coef_

array([ 0.39390555])

In [59]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [60]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [61]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)


In [105]:
from sklearn.linear_model import Ridge
rin_reg = Ridge(alpha=0.2)
rin_reg.fit(X_train, y_train)

Ridge(alpha=0.2, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [106]:
rin_reg.score(X_train, y_train)

0.92027762704370153

In [107]:
rin_reg.score(X_test, y_test)

0.77467835559350828

In [124]:
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [131]:
ridge_reg = Ridge(alpha=0.1)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [132]:
ridge_reg.score(X_train, y_train)

0.92857820820107329

In [133]:
ridge_reg.score(X_test, y_test)

0.77179336888449701

In [134]:
from sklearn.linear_model import LinearRegression

In [135]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [136]:
lin_reg.score(X_train, y_train)

0.95235264368642392

In [137]:
lin_reg.score(X_test, y_test)

0.60577548929354275

In [138]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [139]:
lin_reg.score(X_train, y_train)

0.95235264368642392

In [140]:
lin_reg.score(X_test, y_test)

0.60577548929354275

In [141]:
lin_reg.intercept_

31.645174100827955

In [142]:
lin_reg.coef_

array([ -4.02752236e+02,  -5.00710011e+01,  -1.33316908e+02,
        -1.20021023e+01,  -1.27106873e+01,   2.83052585e+01,
         5.44920273e+01,  -5.17339345e+01,   2.52602789e+01,
         3.64990704e+01,  -1.01038605e+01,  -1.96288897e+01,
        -2.13677312e+01,   1.46473758e+01,   2.89505391e+03,
         1.51026852e+03,   1.17995400e+02,  -2.65658068e+01,
         3.12488451e+01,  -3.14463610e+01,   4.52535825e+01,
         1.28349557e+03,  -2.24600306e+03,   2.22198614e+02,
        -4.66264354e-01,   4.07661992e+01,  -1.34357879e+01,
        -1.90960479e+01,  -2.77605103e+00,  -8.09710327e+01,
         9.73141885e+00,   5.13324280e+00,  -7.87928926e-01,
        -7.60269229e+00,   3.36717627e+01,  -1.15051345e+01,
         6.62672250e+01,  -1.75632324e+01,   4.29826712e+01,
         1.27662043e+00,   6.09633677e-01,   5.71868313e+01,
         1.40823103e+01,   5.53404218e+01,  -3.03481907e+01,
         1.88121756e+01,  -1.37772336e+01,   6.09790464e+01,
        -1.25792000e+01,

In [146]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [177]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001, max_iter=100000)
lasso_reg.fit(X_train, y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=100000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [178]:
lasso_reg.score(X_train, y_train)

0.93966208509270654

In [179]:
lasso_reg.score(X_test, y_test)

0.73965193361212722

In [176]:
(lasso_reg.corf_ != 0).sum()

AttributeError: 'Lasso' object has no attribute 'corf_'

In [170]:
ridge_reg.score(X_train, y_train)

0.94478837099251156

In [171]:
ridge_reg.score(X_test, y_test)

0.70165058002276792

In [166]:
import numpy as np

In [167]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.linear_model import Lasso
lasso_reg = Lasso()
lasso_reg.fit(X_train, y_train)
lasso_reg.score(X_train, y_train) # 0.29323768991114596
lasso_reg.score(X_test, y_test) # 0.2093750325527227
np.sum(lasso_reg.coef_ != 0) # Number of features used - 4


4

In [180]:
(lasso_reg.coef_ != 0).sum()

69

In [181]:
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [191]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.01)
ridge_reg.fit(X_train, y_train)

Ridge(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [192]:
ridge_reg.score(X_train, y_train)

0.94478837099251156

In [193]:
ridge_reg.score(X_test, y_test)

0.70165058002276792

In [194]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X_train, y_train)

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [195]:
import mglearn
X, y = mglearn.datasets.make_forge()

In [196]:
from sklearn.linear_model import LogisticRegression

In [197]:
log_clf = LogisticRegression()
log_clf.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [199]:
(lasso_reg.coef_ != 0).sum()

8

In [200]:
import mglearn
X, y = mglearn.datasets.make_forge()

In [202]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC()
lin_svc.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [203]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [204]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC()
lin_svc.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [205]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [207]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression()
log_clf.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [208]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC()
lin_svc.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [209]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [231]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression(C=0.01)
log_clf.fit(X_train, y_train)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [232]:
log_clf.score(X_train, y_train)

0.93427230046948362

In [233]:
log_clf.score(X_test, y_test)

0.93006993006993011

In [234]:
from sklearn.datasets import make_blobs

X, y = make_blobs(random_state=42)

In [235]:
from sklearn.svm import LinearSVC
lin_svc = LinearSVC(C=1)
lin_svc.fit(X, y)

LinearSVC(C=1, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [239]:
lin_svc.intercept_

array([-1.07745182,  0.13140547, -0.08604809])