In [5]:
from sklearn.model_selection import train_test_split
import mglearn

X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [7]:
from sklearn.linear_model import Ridge

In [9]:
ridge_reg = Ridge(alpha=1)
ridge_reg.fit(X_train, y_train)
ridge_reg.score(X_train, y_train)

0.88605785603958365

In [10]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)

In [12]:
from sklearn.svm import SVC
rbf_clf = SVC(kernel="rbf")
rbf_clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)
lin_reg.score(X_train, y_train)

0.67008903150757559

In [17]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [18]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [19]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(C=1)
log_reg.fit(X, y)
log_reg.score(X, y)

0.92307692307692313

In [20]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [21]:
lin_reg.intercept_

-0.031804343026759746

In [22]:
lin_reg.coef_

array([ 0.39390555])

In [23]:
from sklearn.linear_model import Ridge

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                   random_state=42)
forest_clf = RandomForestClassifier(n_estimators=5, random_state=2)
forest_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=5, n_jobs=1, oob_score=False, random_state=2,
            verbose=0, warm_start=False)

In [26]:
forest_clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=1872583848, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=794921487, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=111352301, splitter='best'),
 DecisionTreeClassifier(

In [27]:
from sklearn.datasets import load_breast_cancer

In [28]:
import mglearn
from sklearn.model_selection import train_test_split
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.linear_model import Lasso
lasso_reg = Lasso()
lasso_reg.fit(X_train, y_train)
lasso_reg.score(X_train, y_train) # 0.29323768991114596
lasso_reg.score(X_test, y_test) # 0.2093750325527227


0.20937503255272272

In [30]:
import numpy as np

In [31]:
np.sum(lasso_reg.coef_ != 0)

4

In [32]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=10)
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [44]:
knn_clf.score(X_train, y_train)

0.89473684210526316

In [45]:
knn_clf.score(X_test, y_test)

0.8571428571428571

In [46]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [47]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [48]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [61]:
import numpy as np

import mglearn
X, y = mglearn.datasets.load_extended_boston()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.01, max_iter=100000)
lasso_reg.fit(X_train, y_train)
lasso_reg.score(X_train, y_train) # 0.29323768991114596


0.89650695597512908

In [62]:
lasso_reg.score(X_test, y_test) # 0.2093750325527227



0.76564898878435228

In [54]:
np.sum(lasso_reg.coef_ != 0) # Number of features used - 4

4

In [63]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [70]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.01, max_iter=10000)
lasso_reg.fit(X_train, y_train)
lasso_reg.score(X_train, y_train)

0.89650695597512908

In [71]:
lasso_reg.score(X_test, y_test)

0.76564898878435228

In [72]:
from sklearn.datasets import load_boston

In [73]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


In [76]:
from sklearn.ensemble import GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(learning_rate=0.1, n_estimators=100, max_depth=5)

In [77]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
X = cancer["data"]
y = cancer["target"]

In [79]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)


In [81]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X_scaled)
X_pca = pca.transform(X_scaled)

In [82]:
from sklearn.preprocessing import MinMaxScaler

In [88]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [89]:
kmeans.labels_

array([2, 2, 2, 0, 2, 0, 2, 0, 0, 0, 2, 2, 2, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       1, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 2, 0, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0,
       2, 1, 0, 1, 0, 0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 1, 0, 0, 0, 0,
       2, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       2, 0, 0, 2, 0, 0, 1, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 2,
       2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0,
       0, 2, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2,

In [91]:
X.shape

(569, 30)

In [92]:
X_pca.shape

(569, 2)

In [93]:
from sklearn.datasets import make_blobs
X, y = make_blobs(random_state=1)


In [94]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)
kmeans.labels_

array([1, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 2, 0, 2,
       1, 0, 2, 2, 1, 1, 2, 1, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 2,
       1, 1, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 1, 1, 0, 2, 2, 0, 0, 2, 1, 2, 1,
       0, 0, 0, 2, 1, 1, 0, 2, 2, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 2, 1,
       1, 0, 0, 2, 2, 1, 2, 1], dtype=int32)

In [96]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [97]:
kmeans.labels_

array([1, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 2, 0, 2,
       1, 0, 2, 2, 1, 1, 2, 1, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 2,
       1, 1, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 1, 1, 0, 2, 2, 0, 0, 2, 1, 2, 1,
       0, 0, 0, 2, 1, 1, 0, 2, 2, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 2, 1,
       1, 0, 0, 2, 2, 1, 2, 1], dtype=int32)

In [98]:
kmeans.predict(X)

array([1, 0, 0, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 2, 0, 2,
       1, 0, 2, 2, 1, 1, 2, 1, 1, 2, 1, 0, 2, 0, 0, 0, 2, 2, 0, 1, 0, 0, 2,
       1, 1, 1, 1, 0, 2, 2, 2, 1, 2, 0, 0, 1, 1, 0, 2, 2, 0, 0, 2, 1, 2, 1,
       0, 0, 0, 2, 1, 1, 0, 2, 2, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 2, 1,
       1, 0, 0, 2, 2, 1, 2, 1], dtype=int32)

In [99]:
np.loadtxt("ssss", delimiter=1)

FileNotFoundError: [Errno 2] No such file or directory: 'ssss'

In [1]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [2]:
from sklearn.svm import SVC
svc_clf = SVC()

In [3]:
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_wave(n_samples=40)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=66)


In [5]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=2)

In [6]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)

from sklearn.ensemble import GradientBoostingClassifier
gbrt = GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train, y_train)

gbrt.score(X_train, y_train) # 1
gbrt.score(X_test, y_test) # 0.95

0.95804195804195802

In [7]:
gbrt.feature_importances_

array([ 0.01337291,  0.04201687,  0.0208666 ,  0.01889077,  0.01028091,
        0.03215986,  0.02074619,  0.11678956,  0.00820024,  0.00074312,
        0.02042134,  0.00680047,  0.02023052,  0.03907398,  0.05406751,
        0.04795741,  0.02358101,  0.00934718,  0.00593481,  0.0239241 ,
        0.05354265,  0.06160083,  0.10961728,  0.07395201,  0.01867851,
        0.03842953,  0.01915824,  0.07128703,  0.01773659,  0.00059199])

In [8]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [9]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [10]:
import mglearn
from sklearn.model_selection import train_test_split
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [17]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


gbrt = GradientBoostingClassifier(learning_rate=0.01, max_depth=2, random_state=0)
gbrt.fit(X_train, y_train)
gbrt.score(X_train, y_train) # 1
gbrt.score(X_test, y_test) # 0.95

0.965034965034965

In [18]:
from sklearn.datasets import make_blobs
X, y = make_blobs(random_state=1)


In [20]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [22]:
kmeans.labels_

array([0, 2, 2, 2, 1, 1, 1, 2, 0, 0, 2, 2, 1, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1,
       0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 1, 2, 2, 2, 1, 1, 2, 0, 2, 2, 1,
       0, 0, 0, 0, 2, 1, 1, 1, 0, 1, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 0, 1, 0,
       2, 2, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 2, 1, 0, 0, 0, 0, 2, 0, 1, 0,
       0, 2, 2, 1, 1, 0, 1, 0], dtype=int32)

In [23]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(cancer["data"], cancer["target"])


In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
X = cancer["data"]
y = cancer["target"]


In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(X)
X_pca = pca.transform(X)

In [27]:
X.shape

(569, 30)

In [28]:
X_pca.shape

(569, 3)

In [29]:
arr.var(axis=0)

NameError: name 'arr' is not defined

In [32]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
np.diag(arr)

array([1, 5, 9])

In [35]:

arr = np.arange(10)

In [36]:
np.diag(arr)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [37]:
np.linalg.det(arr)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [1]:
import numpy as np

In [2]:
arr = np.random.randn(7) * 5
arr

array([-2.709043  ,  6.9218498 ,  5.45149914, -3.17920729, -1.55492475,
        1.44104803,  7.41027387])

In [3]:
np.sqrt(arr)

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([        nan,  2.63094086,  2.33484457,         nan,         nan,
        1.2004366 ,  2.72218182])

In [4]:
X = np.random.randn(5, 5)
X

array([[-0.33816721, -0.04241435, -0.95377871,  1.25583452, -0.35860033],
       [ 0.23305219,  1.21719866, -0.32040344,  0.48799615, -0.46214408],
       [-1.05817618, -0.4456985 , -0.54438865, -0.82468724, -0.20187888],
       [-1.15617179, -2.00485956,  1.49304072, -0.40967789,  0.16116295],
       [ 0.5303833 ,  0.80805002,  1.68286148, -0.15178845, -0.63821128]])

In [5]:
np.diag(X)

array([-0.33816721,  1.21719866, -0.54438865, -0.40967789, -0.63821128])

In [6]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [7]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

In [9]:
arr[[2, 4, 3]]

array([[ 2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.]])

In [10]:
arr = np.random.randn(7) * 5


In [11]:
np.isnan(arr)

array([False, False, False, False, False, False, False], dtype=bool)

In [13]:
arr = np.array([[7, 8, 9], [10, 11, 12]])
arr

array([[ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.hstack([np.zeros((2, 1)), arr])

array([[  0.,   7.,   8.,   9.],
       [  0.,  10.,  11.,  12.]])

In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [16]:
arr2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [17]:
arr2d[2]

array([7, 8, 9])

In [18]:
arr = np.random.randn(2, 2)


In [19]:
np.tile(arr, (2, 1))

array([[-0.19260242, -0.35192912],
       [-0.94096002,  0.05670924],
       [-0.19260242, -0.35192912],
       [-0.94096002,  0.05670924]])

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [21]:
arr.astype(np.int)

array([ 3, -1, -2,  0, 12, 10])

In [22]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [23]:
arr2d[1, :2]

array([4, 5])

In [24]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [25]:
arr.sum(axis=1)

array([ 3, 12, 21, 30])

In [26]:
arr = np.arange(100)

In [28]:
np.random.shuffle(arr)

In [30]:
arr

array([45, 82, 14, 39, 18, 91, 27, 86, 78, 51, 70, 44,  8, 35, 48, 92, 59,
       23, 57, 26, 29, 40, 83, 76, 73, 66, 56, 49, 25,  0, 94, 24, 50, 61,
       36, 11, 98, 41,  7, 21, 97, 87, 46, 32, 95, 64, 65,  2,  9, 88,  4,
        5, 68,  3, 33, 55, 12, 22, 74, 75, 17, 71, 96, 31, 58,  1, 80, 77,
       60, 52, 16, 53, 69, 62, 19, 84, 67, 81, 43, 99, 79, 38, 89, 90,  6,
       10, 15, 34, 37, 85, 20, 47, 30, 42, 28, 93, 13, 72, 54, 63])

In [31]:
np.random.uniform(0, 10, 10)

array([ 2.00412937,  8.64662687,  6.43312405,  5.1801403 ,  7.38535962,
        9.54999084,  7.25412673,  4.67935039,  8.06217218,  0.66693547])

In [32]:
np.arange(32).reshape((8, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [33]:

arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])

In [34]:
np.logical_and(arr1, arr2)

array([False, False,  True], dtype=bool)

In [35]:
np.array([1, 2, 3], dtype=np.float64)

array([ 1.,  2.,  3.])

In [36]:
np.arange(101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
np.random.normal(10, 100, 20)

array([  70.71490837,  -29.8099259 ,   18.32174951,  -25.93554172,
         92.00830436,   41.60851848, -106.2797342 ,  -91.33069621,
        156.54654611, -198.67215889,  -48.19874569, -175.89800718,
        114.59543683, -242.90450702,   62.18243836,   -4.56753638,
        157.16097805,  106.7188451 ,   78.76499277,  100.37505506])

In [38]:
np.in1d([1, 2, 3], [1, 2])

array([ True,  True, False], dtype=bool)

In [39]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)

In [40]:
data[names == "bob"]

array([], shape=(0, 4), dtype=float64)

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.astype(np.float)

array([ 1.,  2.,  3.,  4.,  5.])

In [43]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

arr2 = np.random.randn(3, 2)


In [44]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -0.32966997, -1.36344508],
       [ 2.        ,  3.        , -0.6268393 ,  0.67724692],
       [ 4.        ,  5.        ,  0.3455107 , -0.29576819]])

In [45]:
arr.ndim

1

In [46]:
data = np.zeros((3, 6))

In [47]:
np.empty_like(data)

array([[  1.28822975e-231,  -2.68679651e+154,   4.44659081e-323,
          0.00000000e+000,   0.00000000e+000,   1.15998412e-028],
       [  2.44171989e+232,   8.00801729e+159,   4.62860840e-072,
          1.05089708e-153,   4.04676264e-086,   4.06246466e-144],
       [  3.45365695e+175,   2.20835466e-094,   9.78750380e+199,
          6.97843734e+252,   2.65665617e-312,   1.25160405e-308]])

In [48]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [49]:
arr2d[0, 2]

3

In [50]:
np.ones_like(arr)

array([1, 1, 1, 1, 1, 1])

In [51]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [52]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
arr = np.random.randn(6)

In [54]:
arr.sort()

In [55]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
arr.sort(axis=1)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

arr2 = np.random.randn(3, 2)


In [58]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.30746582, -0.22323493],
       [ 1.2467406 ,  0.95224831],
       [ 0.03823807, -0.46198948]])

In [59]:
arr = np.random.randn(2, 2)


In [62]:
np.repeat(arr, (3, 4), axis=1)

array([[ 1.59903523,  1.59903523,  1.59903523,  0.16714002,  0.16714002,
         0.16714002,  0.16714002],
       [ 0.68695186,  0.68695186,  0.68695186, -0.59682688, -0.59682688,
        -0.59682688, -0.59682688]])

In [63]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [65]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
np.random.seed(1)

In [68]:
np.random.randint(0, 10)

5

In [69]:
arr = np.array([[7, 8, 9], [10, 11, 12]])


In [70]:
np.r_[np.zeros((1, 3)), arr]

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [71]:
np.vstack([np.zeros((1, 3)), arr])

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [72]:
np.concatenate([np.zeros((1, 3)), arr], axis=0)

array([[  0.,   0.,   0.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])

In [73]:
arr1 = np.array([True, False, True])
arr2 = np.array([False, False, True])

In [74]:
np.logical_not(arr1)

array([False,  True, False], dtype=bool)

In [75]:
~arr1

array([False,  True, False], dtype=bool)

In [76]:
a = np.array([6, 0, 0, 4, 2, 5, 6])
b = [2, 3, 6]

In [77]:
np.setdiff1d(a, b)

array([0, 4, 5])

In [78]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
arr.reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
arr1 = np.random.randn(7) * 5

arr2 = np.random.randn(7)


In [81]:
arr1 > arr2

array([False, False,  True, False,  True, False, False], dtype=bool)

In [82]:
np.greater(arr1, arr2)

array([False, False,  True, False,  True, False, False], dtype=bool)

In [83]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [84]:
arr = np.random.randn(2, 2)

In [85]:
np.tile(arr, (1, 2))

array([[ 0.04026035, -0.90312288,  0.04026035, -0.90312288],
       [ 0.17532267,  0.19443089,  0.17532267,  0.19443089]])

In [86]:
bools = np.array([False, False, True, False])

In [87]:
np.any(bools)

True

In [88]:
arr = np.random.randn(2, 2)


In [90]:
np.repeat(arr, (2, 3), axis=1)

array([[-0.53524902, -0.53524902,  0.77735121,  0.77735121,  0.77735121],
       [ 0.17133845,  0.17133845, -0.44285144, -0.44285144, -0.44285144]])

In [91]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [92]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336],
       [  9,  90, 990]])

In [93]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
arr.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [96]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [97]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [98]:
arr.argmax(axis=1)

array([2, 2, 2, 2])

In [99]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])


In [100]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [101]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])


In [102]:
arr.argmax(axis=0)

array([3, 3, 3])

In [103]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))

arr2 = np.random.randn(3, 2)


In [105]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        ,  1.70490377,  0.92434585],
       [ 2.        ,  3.        , -1.30486124, -0.38057504],
       [ 4.        ,  5.        , -0.74362701, -0.43712177]])

In [1]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
gbr = GradientBoostingRegressor(learning_rate=0.1, n_estimators=100, max_depth=)3

In [2]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [4]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression()
log_clf.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [5]:
log_clf.score(X_train, y_train)

0.94736842105263153

In [6]:
log_clf.score(X_test, y_test)

0.8571428571428571

In [7]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [15]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.01, max_iter=1000000)
lasso_reg.fit(X_train, y_train)

Lasso(alpha=0.01, copy_X=True, fit_intercept=True, max_iter=1000000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False)

In [16]:
lasso_reg.score(X_train, y_train)

0.89650695597512908

In [17]:
lasso_reg.score(X_test, y_test)

0.76564898878435228

In [18]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


In [19]:
from sklearn.svm import SVC
rbf_clf = SVC(kernel="rbf")

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                   random_state=42)
forest_clf = RandomForestClassifier(n_estimators=5, random_state=2)
forest_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=5, n_jobs=1, oob_score=False, random_state=2,
            verbose=0, warm_start=False)

In [21]:
forest_clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=1872583848, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=794921487, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=111352301, splitter='best'),
 DecisionTreeClassifier(

In [22]:
forest_clf.feature_importances_

array([ 0.4081634,  0.5918366])

In [23]:
from sklearn.model_selection import train_test_split
import mglearn

X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [24]:
from sklearn.linear_model import Ridge

In [25]:

import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                   random_state=42)


In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
import mglearn
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_forge()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [32]:
from sklearn.neighbors import KNeighborsRegressor

In [33]:

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


In [35]:
from sklearn.ensemble import GradientBoostingClassifier

In [36]:
gbc_clf = GradientBoostingClassifier()
gbc_clf.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [38]:
import pandas as pd
ram_prices = pd.read_csv("datasets/ram_price.csv")
data_train = ram_prices[ram_prices.date < 2000]
data_test = ram_prices[ram_prices.date >= 2000]

X_train = data_train.date[:, np.newaxis]
y_train = np.log(data_train.price)


NameError: name 'np' is not defined

In [39]:
from sklearn.tree import DecisionTreeRegressor

In [40]:
from sklearn.datasets import load_breast_cancer

In [1]:
from sklearn.metrics import accuracy_score

In [4]:
lin_reg.intercept_

NameError: name 'lin_reg' is not defined