In [3]:
import mglearn
from sklearn.model_selection import train_test_split
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [4]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [6]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [7]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


In [18]:
from sklearn.ensemble import GradientBoostingClassifier
gb_clf = GradientBoostingClassifier(max_depth=2, n_estimators=100, learning_rate=0.2)

In [10]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [11]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=1)

In [12]:
lin_reg.intercept_

-0.031804343026759746

In [13]:
lin_reg.coef_

array([ 0.39390555])

In [20]:
gb_clf.important_features_

AttributeError: 'GradientBoostingClassifier' object has no attribute 'important_features_'

In [21]:
from sklearn.svm import LinearSVC

In [22]:
from sklearn.svm import SVC

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


from sklearn.ensemble import GradientBoostingClassifier
gbrt = GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train, y_train)
gbrt.score(X_train, y_train) # 1
gbrt.score(X_test, y_test) # 0.95

0.95804195804195802

In [3]:
gbrt.feature_importances_

array([ 0.01337291,  0.04201687,  0.0208666 ,  0.01889077,  0.01028091,
        0.03215986,  0.02074619,  0.11678956,  0.00820024,  0.00074312,
        0.02042134,  0.00680047,  0.02023052,  0.03907398,  0.05406751,
        0.04795741,  0.02358101,  0.00934718,  0.00593481,  0.0239241 ,
        0.05354265,  0.06160083,  0.10961728,  0.07395201,  0.01867851,
        0.03842953,  0.01915824,  0.07128703,  0.01773659,  0.00059199])

In [4]:
gbrt.important_features_

AttributeError: 'GradientBoostingClassifier' object has no attribute 'important_features_'

In [5]:
from sklearn.datasets import make_blobs

X, y = make_blobs(random_state=42)

In [6]:
from sklearn.svm import LinearSVC
svc_clf = LinearSVC()
svc_clf.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [10]:
svc_clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [11]:
svc_clf.coef_.shape

(3, 2)

In [ ]:
max_depth
n_estimators
max_features

In [12]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
forest_clf = RandomForestClassifier()

In [17]:
from sklearn.linear_model import LogisticRegression
log_clf = LogisticRegression()
log_clf.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=40)


In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
max_depth, n_estimators, learning_rate

In [21]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)

In [22]:
from sklearn.svm import SVC
rbf_clf = SVC(kernel="rbf")

In [23]:
from sklearn.model_selection import train_test_split

X, y = mglearn.datasets.make_wave(n_samples=40)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=66)


In [28]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg = KNeighborsRegressor(n_neighbors=10)
knn_reg.fit(X_train, y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=10, p=2,
          weights='uniform')

In [29]:
knn_reg.score(X_train, y_train)

0.692002710014058

In [30]:
knn_reg.score(X_test, y_test)

0.71008065992032587

In [32]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()

In [33]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [34]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [35]:
tree.feature_importances_

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.01019737,  0.04839825,  0.        ,  0.        ,  0.0024156 ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.72682851,  0.0458159 ,  0.        ,  0.        ,  0.0141577 ,
        0.        ,  0.018188  ,  0.1221132 ,  0.01188548,  0.        ])

In [36]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
import pandas as pd
ram_prices = pd.read_csv("datasets/ram_price.csv")
data_train = ram_prices[ram_prices.date < 2000]
data_test = ram_prices[ram_prices.date >= 2000]
# predict prices based on date
X_train = data_train.date[:, np.newaxis]
# we use a log-transform to get a simpler relationship of data ti target
y_train = np.log(data_train.price)
X_all = ram_prices.date[:, np.newaxis]

In [40]:
import numpy as np

In [41]:
from sklearn.tree import DecisionTreeRegressor

In [43]:
from sklearn.datasets import load_breast_cancer

In [44]:
np.sum(lasso.coef_ != 0)

NameError: name 'lasso' is not defined

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
from sklearn.ensemble import GradientBoostingClassifier
grb_clf = GradientBoostingClassifier()
grb_clf.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [49]:
grb_clf.score(X_train, y_train)

1.0

In [50]:
grb_clf.score(X_test, y_test)

0.95804195804195802

In [51]:
from sklearn.svm import SVC
svc_clf = SVC(kernel="rbf")
svc_clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [52]:
svc_clf.score(X_train, y_train)

1.0

In [53]:
svc_clf.score(X_test, y_test)

0.62937062937062938

In [54]:
np.sum(lasso.coef_ != 0)

NameError: name 'lasso' is not defined

In [55]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1)

In [56]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                   random_state=42)
forest_clf = RandomForestClassifier(n_estimators=5, random_state=2)
forest_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=5, n_jobs=1, oob_score=False, random_state=2,
            verbose=0, warm_start=False)

In [58]:
forest_clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=1872583848, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=794921487, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=111352301, splitter='best'),
 DecisionTreeClassifier(

In [59]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)

from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=4, random_state=0)
tree.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')

In [60]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier()

In [63]:
from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier(n_estimators=100)

In [65]:
import mglearn
X, y = mglearn.datasets.load_extended_boston()
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [66]:
lin_reg.score(X_train, y_train)

0.95235264368642392

In [67]:
lin_reg.score(X_test, y_test)

0.60577548929354275

In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=100, noise=0.25, random_state=3)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y,
                                                   random_state=42)
forest_clf = RandomForestClassifier(n_estimators=5, random_state=2)
forest_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=5, n_jobs=1, oob_score=False, random_state=2,
            verbose=0, warm_start=False)

In [69]:
forest_clf.estimators_

[DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=1872583848, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=794921487, splitter='best'),
 DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
             max_features='auto', max_leaf_nodes=None,
             min_impurity_split=1e-07, min_samples_leaf=1,
             min_samples_split=2, min_weight_fraction_leaf=0.0,
             presort=False, random_state=111352301, splitter='best'),
 DecisionTreeClassifier(

In [70]:
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)



from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=100, random_state=0)
forest.fit(X_train, y_train)

forest.score(X_train, y_train) # 1
forest.score(X_test, y_test) # 0.97


0.97202797202797198

In [72]:
forest.feature_importances_

array([ 0.02515433,  0.01563844,  0.05372655,  0.04861645,  0.00769078,
        0.00936994,  0.05539489,  0.10305394,  0.0065771 ,  0.00282708,
        0.02921459,  0.00607814,  0.01342868,  0.03420174,  0.00360641,
        0.00432096,  0.00448775,  0.00657502,  0.00460597,  0.00627095,
        0.11657269,  0.01603133,  0.16027724,  0.0634688 ,  0.01356448,
        0.01164113,  0.03923725,  0.11711756,  0.01164259,  0.00960721])

In [74]:
import mglearn
X, y = mglearn.datasets.make_wave(n_samples=60)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression().fit(X_train, y_train)


In [75]:
lin_reg.score(X_train, y_train)

0.67008903150757559

In [76]:
lin_reg.score(X_test, y_test)

0.65933685968637001

In [83]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)


gbrt = GradientBoostingClassifier(random_state=0, max_depth=1, n_estimators=100)
gbrt.fit(X_train, y_train)
gbrt.score(X_train, y_train) # 1


0.99061032863849763

In [84]:
gbrt.score(X_test, y_test) # 0.95

0.97202797202797198

In [85]:
from sklearn.tree import DecisionTreeClassifier

In [86]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [87]:
knn_clf.score(X_train, y_train)

0.94131455399061037

In [88]:
knn_clf.score(X_test, y_test)

0.93706293706293708

In [89]:
import mglearn
X, y = mglearn.datasets.make_forge()


In [90]:
from sklearn.svm import SVC

In [92]:
from sklearn.datasets import load_boston

In [94]:
boston = load_boston()

In [95]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [96]:
import mglearn
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, stratify=cancer.target, random_state=42)


In [ ]:
from sklearn.tree import DecisionTreeClassification
tree_clf = DecisionTreeClassification()
tree_clf.fit

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data, cancer.target, random_state=0)

from sklearn.ensemble import GradientBoostingClassifier
gbrt = GradientBoostingClassifier(random_state=0)
gbrt.fit(X_train, y_train)

gbrt.score(X_train, y_train) # 1
gbrt.score(X_test, y_test) # 0.95

0.95804195804195802

In [2]:
gbrt.feature_importances_

array([ 0.01337291,  0.04201687,  0.0208666 ,  0.01889077,  0.01028091,
        0.03215986,  0.02074619,  0.11678956,  0.00820024,  0.00074312,
        0.02042134,  0.00680047,  0.02023052,  0.03907398,  0.05406751,
        0.04795741,  0.02358101,  0.00934718,  0.00593481,  0.0239241 ,
        0.05354265,  0.06160083,  0.10961728,  0.07395201,  0.01867851,
        0.03842953,  0.01915824,  0.07128703,  0.01773659,  0.00059199])

In [3]:
from sklearn.datasets import load_breast_cancer